import type { Product, Order, Farmer, Transporter, Client } from "./store"

export const dummyProducts: Product[] = [
  {
    id: "1",
    name: "Premium Orange Juice",
    description: "Fresh squeezed orange juice from organic oranges. Rich in Vitamin C and natural antioxidants.",
    price: 4.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Juices",
    stock: 150,
    batchId: "OJ-2024-001",
    harvestDate: "2024-01-15",
    expiryDate: "2024-07-15",
    farmer: "Green Valley Farm",
    certifications: ["Organic", "Non-GMO", "Fair Trade"],
  },
  {
    id: "2",
    name: "Strawberry Jam",
    description: "Artisanal strawberry jam made from locally sourced berries. Perfect for breakfast and desserts.",
    price: 6.5,
    image: "/placeholder.svg?height=300&width=300",
    category: "Jams",
    stock: 85,
    batchId: "SJ-2024-002",
    harvestDate: "2024-01-10",
    expiryDate: "2025-01-10",
    farmer: "Berry Fresh Co",
    certifications: ["Organic", "Local"],
  },
  {
    id: "3",
    name: "Apple Compote",
    description: "Traditional apple compote with cinnamon. Made from heritage apples grown in mountain orchards.",
    price: 5.75,
    image: "/placeholder.svg?height=300&width=300",
    category: "Compotes",
    stock: 120,
    batchId: "AC-2024-003",
    harvestDate: "2024-01-08",
    expiryDate: "2024-12-08",
    farmer: "Mountain Orchards",
    certifications: ["Organic", "Heritage Variety"],
  },
  {
    id: "4",
    name: "Mixed Berry Juice",
    description: "Antioxidant-rich blend of blueberries, raspberries, and blackberries. Naturally sweet and healthy.",
    price: 5.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Juices",
    stock: 95,
    batchId: "MBJ-2024-004",
    harvestDate: "2024-01-12",
    expiryDate: "2024-07-12",
    farmer: "Berry Fresh Co",
    certifications: ["Organic", "Antioxidant Rich"],
  },
  {
    id: "5",
    name: "Peach Jam",
    description: "Sweet and aromatic peach jam from sun-ripened peaches. A summer favorite all year round.",
    price: 6.25,
    image: "/placeholder.svg?height=300&width=300",
    category: "Jams",
    stock: 70,
    batchId: "PJ-2024-005",
    harvestDate: "2024-01-05",
    expiryDate: "2025-01-05",
    farmer: "Sunny Farms",
    certifications: ["Organic", "Sun-Ripened"],
  },
  {
    id: "6",
    name: "Pear Compote",
    description: "Delicate pear compote with vanilla notes. Made from carefully selected pears at peak ripeness.",
    price: 5.5,
    image: "/placeholder.svg?height=300&width=300",
    category: "Compotes",
    stock: 110,
    batchId: "PC-2024-006",
    harvestDate: "2024-01-03",
    expiryDate: "2024-12-03",
    farmer: "Mountain Orchards",
    certifications: ["Organic", "Premium Quality"],
  },
]

export const dummyOrders: Order[] = [
  {
    id: "ORD-001",
    items: [
      { product: dummyProducts[0], quantity: 2 },
      { product: dummyProducts[1], quantity: 1 },
    ],
    total: 16.48,
    status: "delivered",
    date: "2024-01-20",
    customerName: "John Smith",
    customerEmail: "john@example.com",
    shippingAddress: "123 Main St, City, State 12345",
  },
  {
    id: "ORD-002",
    items: [
      { product: dummyProducts[2], quantity: 3 },
      { product: dummyProducts[3], quantity: 1 },
    ],
    total: 23.24,
    status: "shipped",
    date: "2024-01-19",
    customerName: "Sarah Johnson",
    customerEmail: "sarah@example.com",
    shippingAddress: "456 Oak Ave, City, State 12345",
  },
  {
    id: "ORD-003",
    items: [
      { product: dummyProducts[4], quantity: 2 },
      { product: dummyProducts[5], quantity: 2 },
    ],
    total: 23.5,
    status: "processing",
    date: "2024-01-18",
    customerName: "Mike Davis",
    customerEmail: "mike@example.com",
    shippingAddress: "789 Pine St, City, State 12345",
  },
]

export const dummyFarmers: Farmer[] = [
  {
    id: "1",
    name: "Green Valley Farm",
    location: "California, USA",
    contact: "maria@greenvalley.com",
    products: ["Oranges", "Lemons"],
    rating: 4.8,
    status: "active",
  },
  {
    id: "2",
    name: "Berry Fresh Co",
    location: "Oregon, USA",
    contact: "sarah@berryfresh.com",
    products: ["Strawberries", "Blueberries", "Raspberries"],
    rating: 4.9,
    status: "active",
  },
  {
    id: "3",
    name: "Mountain Orchards",
    location: "Washington, USA",
    contact: "john@mountainorchards.com",
    products: ["Apples", "Pears"],
    rating: 4.7,
    status: "active",
  },
  {
    id: "4",
    name: "Sunny Farms",
    location: "Georgia, USA",
    contact: "mike@sunnyfarms.com",
    products: ["Peaches", "Plums"],
    rating: 4.6,
    status: "active",
  },
]

export const dummyTransporters: Transporter[] = [
  {
    id: "1",
    name: "FreshLogistics",
    contact: "dispatch@freshlogistics.com",
    vehicles: 12,
    currentDeliveries: 8,
    rating: 4.7,
    status: "active",
  },
  {
    id: "2",
    name: "ColdChain Express",
    contact: "ops@coldchain.com",
    vehicles: 8,
    currentDeliveries: 5,
    rating: 4.5,
    status: "active",
  },
  {
    id: "3",
    name: "AgriTransport",
    contact: "info@agritransport.com",
    vehicles: 15,
    currentDeliveries: 12,
    rating: 4.8,
    status: "active",
  },
]

export const dummyClients: Client[] = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+1 (555) 123-4567",
    address: "123 Main St, City, State 12345",
    registrationDate: "2024-01-15",
    status: "active",
    totalOrders: 12,
    totalSpent: 485.75,
    lastOrderDate: "2024-01-20",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "+1 (555) 234-5678",
    address: "456 Oak Ave, City, State 12345",
    registrationDate: "2024-01-10",
    status: "active",
    totalOrders: 8,
    totalSpent: 324.5,
    lastOrderDate: "2024-01-19",
  },
  {
    id: "3",
    name: "Mike Davis",
    email: "mike.davis@email.com",
    phone: "+1 (555) 345-6789",
    address: "789 Pine St, City, State 12345",
    registrationDate: "2024-01-05",
    status: "active",
    totalOrders: 15,
    totalSpent: 672.25,
    lastOrderDate: "2024-01-18",
  },
  {
    id: "4",
    name: "Emily Wilson",
    email: "emily.wilson@email.com",
    phone: "+1 (555) 456-7890",
    address: "321 Elm St, City, State 12345",
    registrationDate: "2023-12-20",
    status: "active",
    totalOrders: 22,
    totalSpent: 1245.8,
    lastOrderDate: "2024-01-17",
  },
  {
    id: "5",
    name: "David Brown",
    email: "david.brown@email.com",
    phone: "+1 (555) 567-8901",
    address: "654 Maple Ave, City, State 12345",
    registrationDate: "2023-11-15",
    status: "inactive",
    totalOrders: 5,
    totalSpent: 189.25,
    lastOrderDate: "2023-12-10",
  },
]

// Chart data for forecasting
export const salesForecastData = [
  { month: "Jan", actual: 4200, predicted: 4100 },
  { month: "Feb", actual: 3800, predicted: 3900 },
  { month: "Mar", actual: 4500, predicted: 4400 },
  { month: "Apr", actual: 5200, predicted: 5100 },
  { month: "May", actual: 5800, predicted: 5900 },
  { month: "Jun", actual: 6200, predicted: 6100 },
  { month: "Jul", predicted: 6800 },
  { month: "Aug", predicted: 7200 },
  { month: "Sep", predicted: 6900 },
  { month: "Oct", predicted: 6400 },
  { month: "Nov", predicted: 5800 },
  { month: "Dec", predicted: 5200 },
]

export const categoryData = [
  { name: "Juices", value: 45, color: "#10b981" },
  { name: "Jams", value: 35, color: "#f59e0b" },
  { name: "Compotes", value: 20, color: "#8b5cf6" },
]

// IoT sensor data
export const iotData = [
  {
    truckId: "TR-001",
    location: "Highway 101, Mile 45",
    temperature: 4.2,
    humidity: 65,
    status: "optimal",
    lastUpdate: "2 minutes ago",
  },
  {
    id: "TR-002",
    location: "Farm Pickup Point",
    temperature: 3.8,
    humidity: 70,
    status: "optimal",
    lastUpdate: "5 minutes ago",
  },
  {
    truckId: "TR-003",
    location: "Distribution Center",
    temperature: 5.1,
    humidity: 68,
    status: "warning",
    lastUpdate: "1 minute ago",
  },
]
